# Generated by Django 4.1.3 on 2022-11-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_date_time', models.DateTimeField(auto_now=True)),
                ('orders_name', models.CharField(max_length=200)),
                ('orders_phone_num', models.CharField(max_length=15)),
            ],
        ),
    ]
